#!/bin/bash
#@Author Shahriar Shovon
#@Github https://github.com/shovon8/sysmon
printf "%-10s%-15s%-15s%-15s%s\n" "PID" "OWNER" "MEMORY" "CPU" "COMMAND"

function sysmon_main() {
    RAWIN=$(ps -o pid,user,%mem,pcpu,command ax | grep -v PID | awk '/[0-9]*/{print $1 ":" $2 ":" $4 ":" $5}')

    for i in $RAWIN
    do
        PID=$(echo $i | cut -d: -f1)
        OWNER=$(echo $i | cut -d: -f2)
        CPU=$(echo $i | cut -d: -f3)
        COMMAND=$(echo $i | cut -d: -f4)
        MEMORY=$(pmap $PID | tail -n 1 | awk '/[0-9]K/{print $2}')

        printf "%-10s%-15s%-15s%-15s%s\n" "$PID" "$OWNER" "$MEMORY" "$CPU" "$COMMAND"
    done
}

sysmon_main | sort -bnr -k3 | head -n10
echo "------------------------"
sysmon_main | sort -bnr -k4 | head -n10

